import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "tk-statuario",
    slug: "statuario-italian-gloss-tile",
    name: "Statuario Italian Gloss Slab Tile",
    category: "Marble Look Tiles",
    material: "Glazed vitrified tile",
    finish: "High gloss",
    size: "800 x 1600 mm",
    origin: "Morbi, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 189,
    mrpPerSqFt: 249,
    rating: 4.8,
    stockSqFt: 6200,
    isFeatured: true,
    tags: ["living room", "premium", "large format"],
    description: "Large-format white marble look tile with dramatic grey veins for luxury Indian homes and showrooms."
  },
  {
    id: "tk-makrana",
    slug: "makrana-white-marble",
    name: "Makrana White Marble",
    category: "Natural Marble",
    material: "Natural stone",
    finish: "Mirror polished",
    size: "Random slab",
    origin: "Makrana, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 385,
    mrpPerSqFt: 460,
    rating: 4.9,
    stockSqFt: 2800,
    isFeatured: true,
    tags: ["heritage", "pooja room", "luxury"],
    description: "Classic Indian white marble with timeless appeal for villas, mandirs, and premium flooring."
  },
  {
    id: "tk-kota",
    slug: "kota-blue-limestone",
    name: "Kota Blue Limestone",
    category: "Natural Stone",
    material: "Limestone",
    finish: "Honed",
    size: "2 x 2 ft",
    origin: "Kota, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 72,
    mrpPerSqFt: 95,
    rating: 4.6,
    stockSqFt: 9400,
    isFeatured: false,
    tags: ["outdoor", "budget", "anti-skid"],
    description: "Durable blue-grey stone loved across India for balconies, corridors, schools, and outdoor floors."
  },
  {
    id: "tk-terrazzo",
    slug: "jaipur-terrazzo-mosaic",
    name: "Jaipur Terrazzo Mosaic Tile",
    category: "Designer Tiles",
    material: "Cement terrazzo",
    finish: "Matte sealed",
    size: "600 x 600 mm",
    origin: "Jaipur, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 148,
    mrpPerSqFt: 210,
    rating: 4.7,
    stockSqFt: 3600,
    isFeatured: true,
    tags: ["cafe", "statement", "matte"],
    description: "Playful terrazzo pattern for boutique cafes, bathrooms, kitchens, and Instagram-ready corners."
  },
  {
    id: "tk-parking",
    slug: "anti-skid-parking-tile",
    name: "Granite Grip Parking Tile",
    category: "Parking Tiles",
    material: "Vitrified ceramic",
    finish: "Anti-skid",
    size: "400 x 400 mm",
    origin: "Morbi, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 64,
    mrpPerSqFt: 88,
    rating: 4.5,
    stockSqFt: 14500,
    isFeatured: false,
    tags: ["parking", "heavy duty", "value"],
    description: "Heavy duty anti-skid tile built for Indian parking areas, ramps, and high-traffic entrances."
  },
  {
    id: "tk-athangudi",
    slug: "athangudi-chettinad-tile",
    name: "Athangudi Chettinad Heritage Tile",
    category: "Handmade Tiles",
    material: "Handmade cement",
    finish: "Pattern matte",
    size: "10 x 10 inch",
    origin: "Athangudi, Tamil Nadu",
    imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 165,
    mrpPerSqFt: 225,
    rating: 4.8,
    stockSqFt: 1900,
    isFeatured: true,
    tags: ["heritage", "pattern", "handmade"],
    description: "Handmade patterned tile inspired by Chettinad homes, ideal for courtyards and feature flooring."
  },
  {
    id: "tk-onyx",
    slug: "onyx-gold-bookmatch-slab",
    name: "Onyx Gold Bookmatch Slab",
    category: "Luxury Slabs",
    material: "Polished porcelain slab",
    finish: "Mirror gloss",
    size: "1200 x 2400 mm",
    origin: "Morbi, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 245,
    mrpPerSqFt: 330,
    rating: 4.9,
    stockSqFt: 2200,
    isFeatured: true,
    tags: ["feature wall", "luxury", "bookmatch"],
    description: "Gold-veined bookmatch slabs for TV walls, hotel lobbies, reception desks, and premium living rooms."
  },
  {
    id: "tk-wood-plank",
    slug: "teakwood-plank-floor-tile",
    name: "Teakwood Plank Floor Tile",
    category: "Wood Look Tiles",
    material: "Vitrified ceramic",
    finish: "Natural matte",
    size: "200 x 1200 mm",
    origin: "Himmatnagar, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 132,
    mrpPerSqFt: 178,
    rating: 4.7,
    stockSqFt: 5100,
    isFeatured: false,
    tags: ["bedroom", "warm", "plank"],
    description: "Warm wood-look planks with easy tile maintenance for bedrooms, balconies, and cozy family rooms."
  },
  {
    id: "tk-subway",
    slug: "sage-green-subway-wall-tile",
    name: "Sage Green Subway Wall Tile",
    category: "Wall Tiles",
    material: "Glazed ceramic",
    finish: "Soft gloss",
    size: "75 x 300 mm",
    origin: "Khurja, Uttar Pradesh",
    imageUrl: "https://images.unsplash.com/photo-1595514535315-186a70c2d99f?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 118,
    mrpPerSqFt: 155,
    rating: 4.6,
    stockSqFt: 4300,
    isFeatured: false,
    tags: ["kitchen", "backsplash", "green"],
    description: "Soft sage subway tiles for kitchens, powder rooms, cafe counters, and modern backsplash designs."
  },
  {
    id: "tk-bathroom",
    slug: "charcoal-anti-skid-bathroom-tile",
    name: "Charcoal Anti-Skid Bathroom Tile",
    category: "Bathroom Tiles",
    material: "Porcelain tile",
    finish: "Grip matte",
    size: "600 x 600 mm",
    origin: "Morbi, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 96,
    mrpPerSqFt: 135,
    rating: 4.7,
    stockSqFt: 7800,
    isFeatured: true,
    tags: ["bathroom", "anti-skid", "matte"],
    description: "Dense charcoal anti-skid tile for wet areas, shower floors, utility rooms, and compact bathrooms."
  },
  {
    id: "tk-mosaic",
    slug: "moroccan-blue-mosaic-tile",
    name: "Moroccan Blue Mosaic Tile",
    category: "Designer Tiles",
    material: "Glazed ceramic mosaic",
    finish: "Gloss patterned",
    size: "300 x 300 mm sheet",
    origin: "Jaipur, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 176,
    mrpPerSqFt: 240,
    rating: 4.8,
    stockSqFt: 2600,
    isFeatured: true,
    tags: ["mosaic", "blue", "accent"],
    description: "Rich blue patterned mosaic for niches, cafe walls, balconies, bathroom highlights, and bar counters."
  },
  {
    id: "tk-concrete",
    slug: "industrial-concrete-large-format",
    name: "Industrial Concrete Large Format",
    category: "Concrete Look Tiles",
    material: "Full body porcelain",
    finish: "Satin matte",
    size: "1200 x 1200 mm",
    origin: "Morbi, Gujarat",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 154,
    mrpPerSqFt: 205,
    rating: 4.6,
    stockSqFt: 6900,
    isFeatured: false,
    tags: ["office", "minimal", "large format"],
    description: "Minimal concrete-look porcelain for offices, studios, retail floors, and modern apartment interiors."
  },
  {
    id: "tk-granite",
    slug: "black-galaxy-granite",
    name: "Black Galaxy Granite",
    category: "Natural Granite",
    material: "Natural granite",
    finish: "Mirror polished",
    size: "Random slab",
    origin: "Ongole, Andhra Pradesh",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 295,
    mrpPerSqFt: 360,
    rating: 4.8,
    stockSqFt: 3100,
    isFeatured: true,
    tags: ["countertop", "granite", "premium"],
    description: "Deep black granite with golden flecks for kitchen counters, staircases, thresholds, and office reception tops."
  },
  {
    id: "tk-outdoor",
    slug: "sandstone-paver-outdoor-tile",
    name: "Sandstone Paver Outdoor Tile",
    category: "Outdoor Pavers",
    material: "Natural sandstone",
    finish: "Shot blasted",
    size: "300 x 600 mm",
    origin: "Jodhpur, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 84,
    mrpPerSqFt: 118,
    rating: 4.5,
    stockSqFt: 8800,
    isFeatured: false,
    tags: ["outdoor", "garden", "paver"],
    description: "Textured sandstone pavers for terraces, garden paths, patios, pool decks, and farmhouse sit-outs."
  },
  {
    id: "tk-roof",
    slug: "cool-roof-terrace-tile",
    name: "Cool Roof Terrace Tile",
    category: "Terrace Tiles",
    material: "Heat reflective ceramic",
    finish: "Matte white",
    size: "300 x 300 mm",
    origin: "Vijayawada, Andhra Pradesh",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 58,
    mrpPerSqFt: 82,
    rating: 4.4,
    stockSqFt: 12500,
    isFeatured: false,
    tags: ["terrace", "cool roof", "budget"],
    description: "Reflective terrace tile made for Indian summers, useful above bedrooms, offices, and top-floor flats."
  },
  {
    id: "tk-cladding",
    slug: "splitface-stone-wall-cladding",
    name: "Splitface Stone Wall Cladding",
    category: "Wall Cladding",
    material: "Natural quartzite",
    finish: "Rough splitface",
    size: "150 x 600 mm",
    origin: "Udaipur, Rajasthan",
    imageUrl: "https://images.unsplash.com/photo-1600566752229-250ed79470c5?auto=format&fit=crop&w=1200&q=80",
    pricePerSqFt: 126,
    mrpPerSqFt: 168,
    rating: 4.6,
    stockSqFt: 4700,
    isFeatured: false,
    tags: ["facade", "texture", "stone"],
    description: "Rugged stone cladding for exterior facades, compound walls, entrance lobbies, and feature columns."
  }
];

export const categories = ["All", ...Array.from(new Set(products.map((product) => product.category)))];
